### ISSUE TITLE
tcp6 compilation broken on Linux by 04e9c5cd: Replace calls to (legacy) bcopy() with calls to memcpy()

### ISSUE THREAD

**Issue by alvarezp** [fgont/ipv6toolkit#29]
Commit "04e9c5cd: Replace calls to (legacy) bcopy() with calls to memcpy()" broke compilation on Linux.

```
$ make
[...]
gcc  -Wall -o tcp6 tools/tcp6.c libipv6.o -lpcap -lm
tools/tcp6.c: In function ‘main’:
tools/tcp6.c:955:17: error: ‘PROBE_DUMP’ undeclared (first use in this function)
tools/tcp6.c:955:17: note: each undeclared identifier is reported only once for each  function it appears in
tools/tcp6.c:958:17: error: ‘PROBE_SCRIPT’ undeclared (first use in this function)
make: *** [tcp6] Error 1
```

This is the chunk at guilt:

```
@@ -951,32 +950,28 @@ int main(int argc, char **argv){
                                listen_f = 1;
                                break;

-                       case 'v':       /* Be verbose */
-                               (idata.verbose_f)++;
-                               break;
-
                        case 'p':       /* Probe mode */
-                               probe_f=1;
-                               break;
-
-                       case 'x':       /* Number of retrnasmissions */
-                               retrans= atoi(optarg);
-                               retrans_f=1;
-                               break;
-
-                       case 'Y':
                                if(strncmp(optarg, "dump", MAX_CMDLINE_OPT_LEN) == 0){
-                                       debug= DEBUG_DUMP;
+                                       probemode= PROBE_DUMP;
                                }
                                else if(strncmp(optarg, "script", MAX_CMDLINE_OPT_LEN) == 0){
-                                       debug= DEBUG_SCRIPT;
+                                       probemode= PROBE_SCRIPT;
                                }
                                else{
                                        puts("Error: Unknown open mode in '-Y' option");
                                        exit(EXIT_FAILURE);
                                }

-                               debug_f=1;
+                               probemode_f=1;
+                               break;
+
+                       case 'v':       /* Be verbose */
+                               (idata.verbose_f)++;
+                               break;
+
+                       case 'x':       /* Number of retrnasmissions */
+                               retrans= atoi(optarg);
+                               retrans_f=1;
                                break;

                        case 'h':       /* Help */
```
